-- AUTO-GENERATED by matugen — do not edit by hand, edit the template instead
-- Template: ~/.config/matugen/templates/hyprland-colors.lua.template

local M = {}

M.primary   = "ffb599"
M.secondary = "e7beaf"
M.surface   = "1a110e"
M.on_surface = "f1dfd9"

return M
