-- AUTO-GENERATED by matugen — do not edit by hand, edit the template instead
-- Template: ~/.config/matugen/templates/hyprland-colors.lua.template

local M = {}

M.primary   = "aac7ff"
M.secondary = "bec6dc"
M.surface   = "111318"
M.on_surface = "e2e2e9"

return M
