-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- Modular Hyprland config — see ~/.config/hypr/confd/     --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- Remove this line once you're happy with the setup and don't want
-- hyprland-hello popping up each session anymore.
-- hl.config({ autogenerated = true })

require("confd.monitors")
require("confd.env")
-- use confd.appearance for full eye candy. confd.ugly-appearance if you want it.
require("confd.appearance")
-- require("confd.ugly-appearance")
require("confd.input")
require("confd.autostart")
require("confd.keybinds")
require("confd.windowrules")
