-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- Modular Hyprland config — see ~/.config/hypr/conf.d/   --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- Remove this line once you're happy with the setup and don't want
-- hyprland-hello popping up each session anymore.
-- hl.config({ autogenerated = true })

require("confd.monitors")
require("confd.env")
require("confd.appearance")
require("confd.input")
require("confd.autostart")
require("confd.keybinds")
require("confd.windowrules")
